packages:
  - "packages/**"
catalog:
  '@base-ui/react': ^1.4.1
  '@biomejs/biome': 2.4.5
  '@fontsource-variable/figtree': ^5.2.10
  radix-ui: ^1.4.3
  shadcn: ^4.7.0
  usehooks-ts: ^3.1.1

catalogMode: prefer
